var GAME = GAME || {};





GAME.Textures = {
    /*'logo' : {src:'Textures/Logo.png',threeObj:undefined},
    'signup' : {src:'Textures/Signup.png',threeObj:undefined},
    'info' : {src:'Textures/info.png',threeObj:undefined},
    'about' : {src:'Textures/About.png',threeObj:undefined},
    'contact' : {src:'Textures/Contact.png',threeObj:undefined},
    'announcements' : {src:'Textures/Announcements.png',threeObj:undefined},
    'abouttext' : {src:'Textures/AboutText.png',threeObj:undefined},
    'contacttext' : {src:'Textures/ContactText.png',threeObj:undefined},
    'announcementstext' : {src:'Textures/AnnouncementsText.png',threeObj:undefined},*/
    /*'level0layer1' : {src:'Textures/Level0Layer1.png',threeObj:undefined},
    'level0layer2' : {src:'Textures/Level0Layer2.png',threeObj:undefined},
    'level0layer3' : {src:'Textures/Level0Layer3.png',threeObj:undefined},
    'level0layer4' : {src:'Textures/Level0Layer4.png',threeObj:undefined},
    'level-1layer1' : {src:'Textures/Level-1Layer1.png',threeObj:undefined},
    'level-1layer2' : {src:'Textures/Level-1Layer2.png',threeObj:undefined},
    'level-1layer3' : {src:'Textures/Level-1Layer3.png',threeObj:undefined},
    'level-1layer4' : {src:'Textures/Level-1Layer4.png',threeObj:undefined},*/
    'cloud1' : {src:'Textures/cloud1.png',threeObj:undefined},
    'cloud2' : {src:'Textures/cloud2.png',threeObj:undefined},
    'cloud3' : {src:'Textures/cloud3.png',threeObj:undefined},
    'cloud4' : {src:'Textures/cloud4.png',threeObj:undefined},
    'cloud5' : {src:'Textures/cloud5.png',threeObj:undefined},
    'level-3front' : {src:'Textures/Level-3Front.png',threeObj:undefined},
    'level-3middle' : {src:'Textures/Level-3Middle.png',threeObj:undefined},
    'level-2front' : {src:'Textures/Level-2Front.png',threeObj:undefined},
    'level-2middle' : {src:'Textures/Level-2Middle.png',threeObj:undefined},
    'level-2back' : {src:'Textures/Level-2Back.png',threeObj:undefined},
    'level-1middle' : {src:'Textures/Level-1Middle.png',threeObj:undefined},
    'level-1back' : {src:'Textures/Level-1Back.png',threeObj:undefined},
    'level0back' : {src:'Textures/Level0Back.png',threeObj:undefined},
    'level2back' : {src:'Textures/Level2Back.png',threeObj:undefined},
    '-1--2transition' : {src:'Textures/-1--2Transition.png',threeObj:undefined},
    '-2--3transition' : {src:'Textures/-2--3Transition.png',threeObj:undefined},
    '0--1transition' : {src:'Textures/0--1Transition.png',threeObj:undefined},
    '1-2transition' : {src:'Textures/1-2Transition.png',threeObj:undefined},
    'bird1' : {src:'Textures/Bird1.png',threeObj:undefined},
    'bird2' : {src:'Textures/Bird2.png',threeObj:undefined},
    'bush3' : {src:'Textures/Bush3.png',threeObj:undefined},
    'people1' : {src:'Textures/People1.png',threeObj:undefined},
    'people2' : {src:'Textures/People2.png',threeObj:undefined},
    'people3' : {src:'Textures/People3.png',threeObj:undefined},
    'people4' : {src:'Textures/People4.png',threeObj:undefined},
    'planet1' : {src:'Textures/Planet1.png',threeObj:undefined},
    'planet2' : {src:'Textures/Planet2.png',threeObj:undefined},
    'sun' : {src:'Textures/Sun.png',threeObj:undefined},
    'playerwalkcycleright1' : {src:'Textures/playerwalkcycleright1.png',threeObj:undefined},
    'playerwalkcycleright2' : {src:'Textures/playerwalkcycleright2.png',threeObj:undefined},
    'playerwalkcycleright4' : {src:'Textures/playerwalkcycleright4.png',threeObj:undefined},
    'playerwalkcycleleft1' : {src:'Textures/playerwalkcycleleft1.png',threeObj:undefined},
    'playerwalkcycleleft2' : {src:'Textures/playerwalkcycleleft2.png',threeObj:undefined},
    'playerwalkcycleleft4' : {src:'Textures/playerwalkcycleleft4.png',threeObj:undefined},
    'aboutus' : {src:'Textures/About Us.jpg',threeObj:undefined},
    'resources' : {src:'Textures/Resources.jpg',threeObj:undefined},
    'rules&faq' : {src:'Textures/Rules & Faq.jpg',threeObj:undefined},
    'announcements' : {src:'Textures/Announcements.jpg',threeObj:undefined},
    'sponsors' : {src:'Textures/Sponsors.jpg',threeObj:undefined},

    /*'level1layer1' : {src:'Textures/Level1Layer1.png',threeObj:undefined},
    'level1layer2' : {src:'Textures/Level1Layer2.png',threeObj:undefined},
    'level1layer3' : {src:'Textures/Level1Layer3.png',threeObj:undefined},
    'level2layer1' : {src:'Textures/Level2Layer1.png',threeObj:undefined},
    'level2layer2' : {src:'Textures/Level2Layer2.png',threeObj:undefined},
    'level2layer3' : {src:'Textures/Level2Layer3.png',threeObj:undefined},
    'level2layer4' : {src:'Textures/Level2Layer4.png',threeObj:undefined},
    'level-2layer1' : {src:'Textures/Level-2Layer1.png',threeObj:undefined},
    'level-2layer2' : {src:'Textures/Level-2Layer2.png',threeObj:undefined},
    'level-2layer3' : {src:'Textures/Level-2Layer3.png',threeObj:undefined},
    'level0-1transition' : {src:'Textures/Level0-1Transition.png',threeObj:undefined},
    'level0-1transition' : {src:'Textures/Level0-1Transition.png',threeObj:undefined}*/
}